# Generated by Django 4.2.8 on 2024-01-20 00:31

import courses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('complete_description', models.TextField(verbose_name='Descripcion completa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('level', models.CharField(choices=[('BG', 'Principiante'), ('IN', 'Intermedio'), ('AD', 'Avanzado')], max_length=2, verbose_name='level')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='published date')),
                ('picture', models.ImageField(blank=True, max_length=500, null=True, upload_to='users')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='enrollment date')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(verbose_name='order')),
                ('video', models.FileField(max_length=300, upload_to=courses.models.get_upload_to, verbose_name='video')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='duracion')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.CharField(max_length=255, verbose_name='Prerequisito')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(verbose_name='order')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now=True, verbose_name='transaction date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='amount')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='course')),
            ],
        ),
    ]
