# Generated by Django 4.2.8 on 2024-01-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points_required',
            field=models.PositiveIntegerField(default=11, verbose_name='Puntos requeridos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Completado'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Puntaje'),
        ),
    ]
