# Generated by Django 4.2.8 on 2024-01-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preference',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
