# Generated by Django 4.2.8 on 2024-01-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='course',
            name='points_required',
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Correcto'),
        ),
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(max_length=500, null=True, upload_to='users', verbose_name='Imagen'),
        ),
    ]
