# Generated by Django 4.2.8 on 2024-02-05 01:35

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_answer_correct_remove_course_points_required_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='complete_description',
        ),
        migrations.AddField(
            model_name='episode',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.get_upload_file_to, verbose_name='Archivo'),
        ),
    ]
