# Generated by Django 4.2.8 on 2024-02-14 22:14

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=courses.models.get_upload_file_to, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.FileField(max_length=500, upload_to=courses.models.get_upload_to, verbose_name='Video'),
        ),
    ]
